version: '3.8'

services:
  db:
    image: mariadb:10.11
    container_name: drupal_db
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: rootpassword123
      MARIADB_DATABASE: drupal
      MARIADB_USER: drupal
      MARIADB_PASSWORD: drupal123
    volumes:
      - db_data:/var/lib/mysql

  drupal:
    image: drupal:10-php8.1-apache
    container_name: drupal_web
    depends_on:
      - db
    ports:
      - "8080:80"
    restart: unless-stopped
    environment:
      DRUPAL_DB_HOST: db
      DRUPAL_DB_NAME: drupal
      DRUPAL_DB_USER: drupal
      DRUPAL_DB_PASSWORD: drupal123
    volumes:
      - drupal_files:/var/www/html/sites

volumes:
  db_data:
  drupal_files: